# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-13 16:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20180411_2031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='accepted',
            new_name='status',
        ),
    ]
