# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-04 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('1', 'Android Developer'), ('2', 'Designer'), ('3', 'Java Developer'), ('4', 'PHP Developer'), ('5', 'Python Developer'), ('6', 'Rails Developer'), ('8', 'iOS Developer')], default='', max_length=8)),
            ],
        ),
    ]
