# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-16 16:24
from __future__ import unicode_literals

from django.db import migrations



def make_skills(apps, schema_editor):
    Skill = apps.get_model('accounts', 'Skill')
    objs = [
        Skill(name='android'),
        Skill(name='designer'),
        Skill(name='java'),
        Skill(name='php'),
        Skill(name='python'),
        Skill(name='rails'),
        Skill(name='wordpress'),
        Skill(name='ios'),
    ]
    Skill.objects.bulk_create(objs)
    Skill.objects.save()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20180411_1549'),
    ]

    operations = [
        migrations.RunPython(make_skills)
    ]
