# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-16 16:24
from __future__ import unicode_literals

from django.db import migrations

skills = ['android', 'designer', 'java', 'php', 'python', 'rails', 'wordpress', 'ios']


def make_skills(apps, schema_editor):
    Skill = apps.get_model('accounts', 'Skill')

    for skill in skills:
        Skill.objects.create(name=skill)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20180411_1549'),
    ]

    operations = [
        migrations.RunPython(make_skills)
    ]

